---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next13-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: dominwong4/next13-app:~0.0.1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/domwongpaloit/terragrunt_template.git
    targetRevision: staging
    path: app-charts/next13-app-helm-chart
    helm:
      parameters:
        - name: "namespace"
          value: "next13-app-staging"
        - name: "ingressClassName"
          value: "external-ingress-nginx"
        - name: "image.name"
          value: "dominwong4/next13-app"
        - name: "image.tag"
          value: "0.0.3"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
