# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
    region = "ap-southeast-1"
}

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = ">=2.6.0"
    }
    aws = {
      source = "hashicorp/aws"
      version = "4.67.0"
    }
  }

  required_version = "~> 1.0"
}

