FROM --platform=linux/amd64 node:20

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied 
COPY package*.json ./

RUN npm install

# Copy source code 
COPY . .

# For hot reloading:
# RUN npm run dev

# For compiled app: 
RUN npm run build 

# Expose port 3000
EXPOSE 3000

# Run the app 
CMD [ "npx" ,"node", "./src/server.js" ]