apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-app
  namespace: staging
  labels:
    prometheus: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: express-app
  endpoints:
    - path: /metrics
      interval: 15s
      scrapeTimeout: 10s
