{
 "title": "Kubernetes Monitoring Dashboard Test",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/express-app(/|$)(.*)\"}[1m]))",
     "legendFormat": "Express app"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/flask-app(/|$)(.*)\"}[1m]))",
     "legendFormat": "Flask app"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_requests{path=\"/express-app(/|$)(.*)\",status=~'2..'}) / sum (nginx_ingress_controller_requests{path=\"/express-app(/|$)(.*)\"}) * 100",
     "legendFormat": "Express app Success Rate (2XX)"
    },
    {
     "expr": "sum(nginx_ingress_controller_requests{path=\"/flask-app(/|$)(.*)\",status=~'2..'}) / sum (nginx_ingress_controller_requests{path=\"/flask-app(/|$)(.*)\"}) * 100",
     "legendFormat": "Flask app Success Rate (2XX)"
    }
   ]
  },
  { "title": "Number of Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Express app",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"express-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask app",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"flask-app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "CPU & Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"express-app\"}[1m])) / count(kube_pod_container_info{container=\"express-app\"})",
     "legendFormat": "Express app"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"flask-app\"}[1m])) / count(kube_pod_container_info{container=\"flask-app\"})",
     "legendFormat": "Flask app"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum (container_memory_working_set_bytes{container=\"express-app\"}))",
     "legendFormat": "Express app"
    },
    {
     "expr": "avg(sum (container_memory_working_set_bytes{container=\"flask-app\"}))",
     "legendFormat": "Flask app"
    }
   ]
  }
 ]
}