apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    job: {{ .Values.appName }}
    app: {{ .Values.appName }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 3000
